function [NameArray,ValueArray] = getData(obj,t)
NameArray = { 'CameraPosition',...
              'CameraTarget',...
              'CameraUpVector',...
              'CameraViewAngle',...
              'Projection',...
              'Clipping',...
              'ClippingStyle',...
              'XLim',...
              'YLim',...
              'ZLim',...
              'XLimMode',...
              'YLimMode',...
              'ZLimMode'};
[P,T,U,A,J,C,S,X,Y,Z] = obj.fetchData(t);
ValueArray = { P,T,U,A,J,C,S,X,Y,Z,'manual','manual','manual' };
end