function [ax] = CreateForegroundAxes3D(h,varargin)
if( nargin == 0 || isempty(h) )
    h = axes;
end
if(isfigure(h))
    fig = h;
    ax  = axes(fig);
else
    if(isaxes(h))
        fig = h.Parent;
        ax  = h;
    else
        fig = ancestor(h,'figure');
        ax  = ancestor(h,'axes');
        if(isempty(fig))
            return;
        end
    end
end
NA = {'Color',...
      'Parent',...
      'HandleVisibility',...
      'PickableParts',...
      'HitTest',...
      'Units', ...
      'Position', ...
      'Visible',...
      'XLimMode',...
      'XLim', ...
      'YLimMode',...
      'YLim', ...
      'XTick','YTick', ...
      'Box',...
      'Clipping',...
      'NextPlot'};
VA = {'none',...
      fig, ...
      'off',...
      'none',...
      'off',...
      'normalized', ...
      [0, 0, 1, 1], ...
      'off', ...
      'manual',...
      [0, 1], ...
      'manual',...
      [0, 1], ...
      [],...
      [], ...
      'off',...
      'off',...
      'add'};
set( ax, NA, VA, varargin{:} );
uistack(ax,'top');
end