function [ax] = figure_radial_gradient(fig,CData)
if( nargin < 2 )
    CData = [1 1 1; 0.6 0.6 0.6];
end
ax = axes( ...
'Color','none',...
'Parent',           fig, ...
'HandleVisibility', 'off',...
'PickableParts',    'none',...
'HitTest',          'off',...
'Units',            'normalized', ...
'Position',         [0, 0, 1, 1], ...
'Visible',          'off', ...
'XLimMode', 'manual', 'XLim',  [0, 1], ...
'YLimMode', 'manual', 'YLim',  [0, 1], ...
'XTick',    [],       'YTick', [], ...
'Box','off',...
'Clipping','off',...
'NextPlot', 'add');
% [P,T] = triangle_fan(16,Inf);
% patch('Faces',T,...
%     'Vertices',P,...
%     'Parent', ax,...
%     'FaceColor','interp',...
%     'FaceVertexCData',[CData(2,:);repmat(CData(1,:),row(P)-1,1)],...
%     'EdgeColor','none');
% [X,Y] = meshgrid(linspace(-1,1,512));
% C = clamp(arrayfun(@(x,y) norm([x y]), X, Y),0,1);
% C = interp1([0 1],CData,C);
% imagesc(ax,C,'XData',[0,1],'YData',[0,1]);
[C] = imread('IMG/Background.png','png');
imagesc(ax,C,'XData',[0,1],'YData',[0,1]);
end