function [ax] = figure_linear_gradient(fig,CData)
if( nargin < 2 )
    CData = [0.6 0.6 0.6; 1 1 1];
end
ax = axes( ...
'Color',            'none',...
'Parent',           fig, ...
'HandleVisibility', 'off',...
'PickableParts',    'none',...
'HitTest',          'off',...
'Units',            'normalized', ...
'Position',         [0, 0, 1, 1], ...
'Visible',          'off', ...
'XLimMode', 'manual', 'XLim',  [0, 1], ...
'YLimMode', 'manual', 'YLim',  [0, 1], ...
'XTick',    [],       'YTick', [], ...
'Box','off',...
'Clipping','off',...
'NextPlot', 'add');
X = [0, 1, 1, 0];
Y = [0, 0, 1, 1];
patch(X, Y, Y,...
    'Parent', ax,...
    'FaceColor','interp',...
    'FaceVertexCData',repelem(CData,2,1),...
    'EdgeColor','none');
end