function [M,T] = xquad(T,iter)
i = 1; j = 2; k = 3; l = 4;
scheme = struct('E',[i i i i; i i j j; i j k l; i i l l; ...
          j j j j; j j k k; i j k l; j j i i;...
          k k k k; k k l l; i j k l; k k j j; ...
          l l l l; l l i i; i j k l; l l k k],'T',4);
[M,T] = xmesh(T,scheme,iter);
end