function [h] = boneLine(length,frame,varargin)
P = [0 0 0; 0 0 length];
T = [1 2 1];
f = @(d) d(1:end-1);
P = cell2mat(cellfun(@(p) f((frame * [p 1]')'),num2cell(P,2),'UniformOutput',false));
N = zeros(size(P));
h = patch('Faces',T,...
          'Vertices',P,...
          'VertexNormals',N,...
          'FaceColor','k',...
          'EdgeColor','k',...
          'FaceLighting','none',...
          varargin{:});
end