function [h] = connect_axes( h, varargin )
if(~isaxes(h))
    error(['Handle type mismatch. Expected ''Axes'', got ',class(h)]);
end
h = linkprop(h,...
[varargin,...
{'XDir',...
'YDir',...
'ZDir',...
'XScale',...
'YScale',...
'ZScale',...
'XLim',...
'YLim',...
'ZLim',...
'CameraPosition',...
'CameraPositionMode',...
'CameraTarget',...
'CameraTargetMode',...
'CameraUpVector',...
'CameraUpVectorMode',...
'CameraViewAngle',...
'CameraViewAngleMode',...
'View',...
'Clipping',...
'ClippingStyle'}]);
end