function [a] = consoleText(fig,text,varargin)
a = annotation(fig,'textbox',...
               'String',text,...
               'Position',[0 0 1 1],...
               'Color',Gray(),...
               'Interpreter','latex',...
               'EdgeColor','none',...
               'VerticalAlignment','bottom',...
               'PickableParts','none',...
               'HitTest','off',...
               varargin{:});
end