function [TargetHandle] = copy_axes_properties(SourceHandle,TargetHandle)
PropName = {'Position',...
            'Clipping',...
            'View',...
            'Projection',...
            'CameraPosition',...
            'CameraTarget',...
            'CameraUpVector',...
            'CameraViewAngle',...
           };
copy_properties(SourceHandle,TargetHandle,PropName);
end