function [varargout] = mat2plane(M,Limits,varargin)
if( nargin < 2 || isempty(Limits) )
    Limits = [ones(2,1) size(M)'];
end
[varargout{1:nargout}] = contourf(M,...
                         linspace(minimum(M),maximum(M),11),...
                         'LineColor','k',...
                         'XData',linspace(Limits(1,1),Limits(1,2),col(M)),...
                         'YData',linspace(Limits(2,1),Limits(2,2),row(M)),...
                         varargin{:});
end