function [P] = transform_point(T,P,type)
if(strcmpi(type,'mat'))
    P = [dotN(T(:,1: 3),P)+T(:, 4) ...
         dotN(T(:,5: 7),P)+T(:, 8) ...
         dotN(T(:,9:11),P)+T(:,12)];
    return;
end
if(strcmpi(type,'dq'))
% P = bsxfun(@plus,...
%            P,...
%            2 * (...
%            bsxfun(@minus,...
%            bsxfun(@plus,...
%                   cross( T(:,2:4), ...
%                          bsxfun(@plus,...
%                                 bsxfun(@plus,cross(T(:,2:4),P,2),P .* T(:,1)),...
%                                 T(:,6:8)),...
%                          2),...
%                   T(:,6:8) .* T(:,1)),...
%            T(:,2:4) .* T(:,5))...
%     ));

P = P + 2 * (...
             + cross( T(:,2:4), cross(T(:,2:4),P,2) + P .* T(:,1) + T(:,6:8),2)... 
             + T(:,6:8) .* T(:,1)...
             - T(:,2:4) .* T(:,5)...
            );
    return;
end
end