function [PP,NN] = apply_dualquaternion(P,N,DQ)
R = realdq(DQ);
I = imagdq(DQ);
PP = P + 2 * (...
    + cross( R(:,2:4), cross(R(:,2:4),P,2) + P .* R(:,1) + I(:,2:4), 2)...
    + I(:,2:4) .* R(:,1)...
    - R(:,2:4) .* I(:,1)...
);
NN = N + 2 * cross( R(:,2:4), cross( R(:,2:4),N,2) + N * R(:,1), 2 );
end