function [ G ] = compute_barycentric_gradient( T, F, A, l )
[I,J,K] = tri2ind(T);
Eij = [0, 1, 0] - [1, 0, 0];
Ejk = [0, 0, 1] - [0, 1, 0];
Eki = [1, 0, 0] - [0, 0, 1];
N   = repmat(normr( cross(Eij, -Eki, 2) ), row(T), 1);
dF  = (  ...
        ( F(I) .* cross(N, l(:,1) .* Ejk, 2) ) + ...
        ( F(J) .* cross(N, l(:,2) .* Eki, 2) ) + ...
        ( F(K) .* cross(N, l(:,3) .* Eij, 2) ) ...
      ) ...
     ./ ( 2 * A );
% G   = full(normr(-dF));
G   = full(-dF);
end