function min_script()
syms pi_x pi_y pi_z ...
     pj_x pj_y pj_z ...
     pk_x pk_y pk_z ...
     si_x si_y si_z ...
     sj_x sj_y sj_z ...
     sk_x sk_y sk_z ...
     di_x di_y di_z ...
     dj_x dj_y dj_z ...
     dk_x dk_y dk_z ...
     a;
P = [[pi_x;pi_y;pi_z],...
     [pj_x;pj_y;pj_z],...
	 [pk_x;pk_y;pk_z]];
S = [[si_x;si_y;si_z],...
     [sj_x;sj_y;sj_z],...
     [sk_x;sk_y;sk_z]];
d = [[di_x;di_y;di_z],...
     [dj_x;dj_y;dj_z],...
     [dk_x;dk_y;dk_z]];

X = S-P;

e = (transpose(X(:,1)+a*d(:,1))*(X(:,1)+a*d(:,1)))+...
    (transpose(X(:,2)+a*d(:,2))*(X(:,2)+a*d(:,2)))+...
    (transpose(X(:,3)+a*d(:,3))*(X(:,3)+a*d(:,3)));

f = solve(simplify(diff(e,a))==0,a);

(di_x*(pi_x - si_x) +...
 di_y*(pi_y - si_y) +...
 di_z*(pi_z - si_z) +...
 dj_x*(pj_x - sj_x) +...
 dj_y*(pj_y - sj_y) +...
 dj_z*(pj_z - sj_z) +...
 dk_x*(pk_x - sk_x) +...
 dk_y*(pk_y - sk_y) +...
 dk_z*(pk_z - sk_z))...
 /...
 (di_x^2 +...
  di_y^2 +...
  di_z^2 +...
  dj_x^2 +...
  dj_y^2 +...
  dj_z^2 +...
  dk_x^2 +...
  dk_y^2 +...
  dk_z^2)


end