h = figure;

x = [];
x = [x; subplot(1,4,numel(x)+1)];
display_mesh(P,N,T,AA);
axis([px(1) px(2) py(1) py(2) pz(1) pz(2)]);

x = [x; subplot(1,4,numel(x)+1)];
display_mesh(P,N,T,F(:,1).*AA);
axis([px(1) px(2) py(1) py(2) pz(1) pz(2)]);

x = [x; subplot(1,4,numel(x)+1)];
display_mesh(P,N,T,I.*AA);
axis([px(1) px(2) py(1) py(2) pz(1) pz(2)]);

x = [x; subplot(1,4,numel(x)+1)];
display_mesh(P,N,T,AA.*DD);
axis([px(1) px(2) py(1) py(2) pz(1) pz(2)]);

linkprop(x,...
{'XDir',...
'YDir',...
'ZDir',...
'XScale',...
'YScale',...
'ZScale',...
'XLim',...
'YLim',...
'ZLim',...
'CameraPosition',...
'CameraPositionMode',...
'CameraTarget',...
'CameraTargetMode',...
'CameraUpVector',...
'CameraUpVectorMode',...
'CameraViewAngle',...
'CameraViewAngleMode',...
'View',...
'Clipping',...
'ClippingStyle'});