function [U] = shadow_map(UV, D, texture)
d = interp2(...
    linspace(0,1,col(texture)),...
    linspace(0,1,row(texture)),...
    texture,...
    1-UV(:,1)/2,1-UV(:,2)/2,'linear',1);
U = 1-abs(D-d);
end