function [P,N,T] = split_edge(P,N,T,ID)
for iter = 1 : 3
    i = iter;
    j = mod(i+1,3);
    k = mod(i+2,3);
    index = find( ...
                    ( ( ID(:,1) == T(:,i) & ID(:,2) == T(:,j) ) |...
                    ( ID(:,1) == T(:,j) & ID(:,2) == T(:,i) ) ) & ...
                    ( ( ID(:,1) == T(:,j) & ID(:,2) == T(:,k) ) |...
                    ( ID(:,1) == T(:,k) & ID(:,2) == T(:,j) ) ) ...
                );
end
end