classdef PlayerControlTool < SharedDataComponent
    properties( Access = public )
        FigureHandle
    end
    
    properties( Access = private, Hidden = true )
        TimeBar
        Play
        Pause
        Stop
        Loop
        Timer
        Speed
        Frame
    end
    
    properties( Access = private, Hidden = true )
        timeListener
    end
    
    methods( Access = public, Sealed = true )
        function [obj] = PlayerControlTool(varargin)
            obj@SharedDataComponent(varargin{:});
            fig = figure('Name','Player Control Tool',...
                         'Resize','off',...
                         'NumberTitle','off',...
                         'MenuBar', 'none',...
                         'ToolBar','none',...
                         'Units','pixels');
            fig.Position = [fig.Position(1:2) 350 50];
            fig.Units = 'normalized';
            ax = CreateAxes3D(fig);
            
            registerProps(obj);
            
            obj.TimeBar = uicontrol( fig,...
                    'Units', 'normalized',...
                    'Style', 'slider',...
                    'Position', [0.1 0.5 0.7 0.4],...
                    'Min', 0,...
                    'Max', 1,...
                    'SliderStep', [0.01 0.1],...
                    'Value', 0);
                
            obj.Loop = uicontrol(fig,...
                'Style','togglebutton',...
                'String','Loop',...
                'Units','normalized',...
                'Position',[obj.TimeBar.Position(1) 0.1 0.2333 0.4],...
                'Visible','on');
            
            obj.Play = uicontrol(fig,...
                'Style','pushbutton',...
                'String','Play',...
                'Units','normalized',...
                'Position',[sum(obj.Loop.Position([1 3])) obj.Loop.Position(2:4)],...
                'Visible','on',...
                'Callback',@(varargin) onPlay(obj));
            
            obj.Pause = uicontrol(fig,...
                'Style','pushbutton',...
                'String','Pause',...
                'Units','normalized',...
                'Position',obj.Play.Position,...
                'Visible','off',...
                'Callback',@(varargin) onPause(obj));
            
            obj.Stop = uicontrol(fig,...
                'Style','pushbutton',...
                'String','Stop',...
                'Units','normalized',...
                'Position',[sum(obj.Play.Position([1 3])) obj.Play.Position(2:4)],...
                'Visible','on',...
                'Callback',@(varargin) onStop(obj));
            
            obj.Speed = uicontrol(fig,...
                'Style','edit',...
                'String','1',...
                'Units','normalized',...
                'Position',[0.8 0.1 0.1 0.38],...
                'Visible','on',...
                'Callback',@(varargin) onSpeed(obj));
            
            obj.Frame = uicontrol(fig,...
                'Style','edit',...
                'String','0',...
                'Units','normalized',...
                'Position',[0.8 0.5 0.1 0.38],...
                'Visible','on',...
                'Callback',@(o,e) set(obj.TimeBar,'Value',str2double(o.String)));
            
%             addlistener( obj.TimeBar, 'Value', 'PostSet',...
%                          @(varargin) changeTimeBar(obj,obj.TimeBar.Value) );
%             addlistener( obj.TimeBar, 'Value', 'PostSet',...
%                          @(varargin) set(obj.Frame,'String',num2str(round(obj.TimeBar.Value,2))) );
%             
            obj.timeListener = addlistener(...
                obj.TimeBar,...
                'Value', 'PostSet',...
                @(varargin) cellfun(@(x) feval(x),...
                {...
                 @() changeTimeBar(obj,obj.TimeBar.Value),...
                 @() set(obj.Frame,'String',num2str(round(obj.TimeBar.Value,2)))...
                },'UniformOutput',false));
                     
            obj.Timer = timer('Period',0.016*2,...
                'TimerFcn', @(varargin) onAdvanceTime(obj),...
                'ExecutionMode', 'fixedSpacing');
            
            obj.FigureHandle = fig;
        end
    end
    
    methods( Access = public )
        function registerProps(obj)
            addProps(obj,'frameTime');
        end
    end
    
    methods( Access = public )
        function changeTimeBar(obj,frame)
            setProps(obj,'frameTime',frame);
        end
        
        function delete(obj)
            if(isvalid(obj.Timer))
                stop(obj.Timer);
            end
            delete(obj.Timer);
            delete(obj.timeListener);
        end
    end
    
    methods( Access = private )
        function onPlay(obj)
            obj.Play.Visible  = 'off';
            obj.Pause.Visible = 'on';
            start(obj.Timer);
        end
        
        function onPause(obj)
            obj.Play.Visible  = 'on';
            obj.Pause.Visible = 'off';
            stop(obj.Timer);
        end
        
        function onStop(obj)
            stop(obj.Timer);
            obj.Play.Visible  = 'on';
            obj.Pause.Visible = 'off';
            obj.TimeBar.Value = obj.TimeBar.Min;
        end
        
        function onAdvanceTime(obj)
            t = obj.TimeBar.Value+obj.TimeBar.SliderStep(1);
            if(t>obj.TimeBar.Max)
                if(obj.Loop.Value == 0)
                    onPause(obj);
                    onStop(obj);
                else
                    set(obj.TimeBar,'Value',obj.TimeBar.Min);
                end
            else
                set(obj.TimeBar,'Value',t);
            end
        end
        
        function onSpeed(obj)
            Max = 0.1;
            Min = 0.01;
            s   = str2double(obj.Speed.String);
            set(obj.TimeBar,'SliderStep',s*[Min Max]);
        end
    end
end
